ARG FUNCTION_DIR="/home/app/"
ARG RUNTIME_VERSION="3.8"

FROM python:${RUNTIME_VERSION}-slim AS python-slim
RUN python${RUNTIME_VERSION} -m pip install --upgrade pip
FROM python-slim AS build-image
ARG FUNCTION_DIR
ARG RUNTIME_VERSION
RUN mkdir -p ${FUNCTION_DIR}
RUN apt-get update && \
    apt-get install -y cmake build-essential autoconf automake libtool curl && \
    rm -rf /var/lib/apt/lists/*
RUN python${RUNTIME_VERSION} -m pip install awslambdaric --target ${FUNCTION_DIR}
FROM python-slim
ARG FUNCTION_DIR
WORKDIR ${FUNCTION_DIR}
COPY --from=build-image ${FUNCTION_DIR} ${FUNCTION_DIR}

# Add Lambda Runtime Interface Emulator for local testing
ADD https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie /usr/bin/aws-lambda-rie
RUN chmod 755 /usr/bin/aws-lambda-rie

RUN apt-get update && \
    apt-get install -y ffmpeg && \
    rm -rf /var/lib/apt/lists/*
COPY requirements.txt ${FUNCTION_DIR}
RUN python${RUNTIME_VERSION} -m pip install -r requirements.txt --target ${FUNCTION_DIR}
COPY entry.sh /
RUN chmod +x /entry.sh
COPY handler.py ${FUNCTION_DIR}
ENTRYPOINT ["/entry.sh"]
CMD ["handler.lambda_handler"]
